#!/bin/bash
# Write Config/Version.xcconfig from version.properties.
set -euo pipefail

if [[ -n "${SRCROOT:-}" ]]; then
  ROOT="$SRCROOT"
else
  ROOT="$(cd "$(dirname "$0")/.." && pwd)"
fi
PROPS="$ROOT/version.properties"
OUT="$ROOT/Config/Version.xcconfig"

if [[ ! -f "$PROPS" ]]; then
  cp "$ROOT/version.properties.example" "$PROPS"
fi

major=$(grep -E '^VERSION_MAJOR=' "$PROPS" | head -1 | cut -d= -f2 | tr -d '[:space:]')
patch=$(grep -E '^VERSION_PATCH=' "$PROPS" | head -1 | cut -d= -f2 | tr -d '[:space:]')
code=$(grep -E '^VERSION_CODE=' "$PROPS" | head -1 | cut -d= -f2 | tr -d '[:space:]')
major=${major:-1}
patch=${patch:-1}
code=${code:-1}
name=$(printf "%d.%03d" "$major" "$patch")

cat > "$OUT" <<EOF
// Generated by scripts/sync-version.sh from version.properties. Do not edit by hand.
MARKETING_VERSION = ${name}
CURRENT_PROJECT_VERSION = ${code}
EOF

echo "version ${name} (${code})"
