#!/bin/bash
# Read app-config.json (or app-config.example.json) and bake it into the iOS target.
# Same keys and defaults as the Android app/build.gradle config loader.
set -euo pipefail

if [[ -n "${SRCROOT:-}" ]]; then
  ROOT="$SRCROOT"
else
  ROOT="$(cd "$(dirname "$0")/.." && pwd)"
fi
python3 - "$ROOT" <<'PY'
import json, sys
from pathlib import Path

root = Path(sys.argv[1])
real = root / "app-config.json"
template = root / "app-config.example.json"
source = real if real.exists() else template
if not source.exists():
    raise SystemExit(f"缺少配置文件: {template}")
try:
    data = json.loads(source.read_text(encoding="utf-8"))
except json.JSONDecodeError as exc:
    raise SystemExit(f"壳包配置文件解析失败: {source.name}，请检查 JSON 格式 -> {exc}") from exc

def config_str(key, default):
    value = data.get(key)
    return default if value is None else str(value)

def config_bool(key, default):
    value = data.get(key)
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    return str(value).lower() == "true"

def config_int(key, default):
    value = data.get(key)
    return default if value is None else int(value)

application_id = config_str("application_id", "com.xj28a.app")
app_name = config_str("app_name", "新记")
web_url = config_str("web_url", "https://test.kaixin28.com")
remote_config_url = config_str("remote_config_url", "")
enable_remote_url = config_bool("enable_remote_url", True)
remote_config_cache_hours = config_int("remote_config_cache_hours", 1)
show_privacy = config_bool("show_privacy_on_first_launch", True)
privacy_policy_url = config_str("privacy_policy_url", "")
show_guide = config_bool("show_guide_on_first_launch", True)
enable_video = config_bool("enable_video_splash", False)
splash_ms = config_int("splash_duration_ms", 2500)
pull_to_refresh = config_bool("enable_pull_to_refresh", True)
user_agent_name = config_str("user_agent_name", "XJ28App")

def swift_str(value):
    return value.replace("\\", "\\\\").replace('"', '\\"')

def swift_bool(value):
    return "true" if value else "false"

swift = f'''import Foundation

/// Generated by scripts/sync-config.sh from {source.name}. Do not edit by hand.
enum AppConfig {{
    static let applicationId = "{swift_str(application_id)}"
    static let appName = "{swift_str(app_name)}"
    static let webURL = "{swift_str(web_url)}"
    static let remoteConfigURL = "{swift_str(remote_config_url)}"
    static let enableRemoteURL = {swift_bool(enable_remote_url)}
    static let remoteConfigCacheHours = {remote_config_cache_hours}
    static let showPrivacyOnFirstLaunch = {swift_bool(show_privacy)}
    static let privacyPolicyURL = "{swift_str(privacy_policy_url)}"
    static let showGuideOnFirstLaunch = {swift_bool(show_guide)}
    static let enableVideoSplash = {swift_bool(enable_video)}
    static let splashDurationMs = {splash_ms}
    static let enablePullToRefresh = {swift_bool(pull_to_refresh)}
    static let userAgentName = "{swift_str(user_agent_name)}"
}}
'''
(root / "XinJi28" / "AppConfig.swift").write_text(swift, encoding="utf-8")

def xc_quote(value):
    if any(ch.isspace() for ch in value) or any(ch in value for ch in '"\\'):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value

xcconfig = f'''// Generated by scripts/sync-config.sh from {source.name}. Do not edit by hand.
#include "Version.xcconfig"
PRODUCT_BUNDLE_IDENTIFIER = {xc_quote(application_id)}
APP_DISPLAY_NAME = {xc_quote(app_name)}
'''
(root / "Config" / "App.xcconfig").write_text(xcconfig, encoding="utf-8")

if not real.exists():
    print(f">>> 提示: 未找到 app-config.json，正在使用模板 app-config.example.json")
print(
    f">>> App 配置[{source.name}]: NAME={app_name} | ID={application_id} | "
    f"WEB_URL={web_url} | REMOTE={str(enable_remote_url).lower()} | "
    f"SHOW_PRIVACY={str(show_privacy).lower()} | SHOW_GUIDE={str(show_guide).lower()} | "
    f"VIDEO_SPLASH={str(enable_video).lower()}"
)
PY
