import Foundation

/// Generated by scripts/sync-config.sh from app-config.example.json. Do not edit by hand.
enum AppConfig {
    static let applicationId = "com.xj28a.app"
    static let appName = "新记"
    static let webURL = "https://test.kaixin28.com"
    static let remoteConfigURL = "https://test.kaixin28.com/app-config.json"
    static let enableRemoteURL = true
    static let remoteConfigCacheHours = 1
    static let showPrivacyOnFirstLaunch = true
    static let privacyPolicyURL = ""
    static let showGuideOnFirstLaunch = true
    static let enableVideoSplash = false
    static let splashDurationMs = 2500
    static let enablePullToRefresh = true
    static let userAgentName = "XJ28App"
}
